<?php

namespace FitatuBundle\Repository;

use FitatuBundle\Entity\Product;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneProductInCart(
        Product $product,
        int $cartId,
        int $clientId
    ) {
        return $this->findOneBy(array(
            'product' => $product,
            'cartId' => $cartId,
            'clientId' => $clientId
        ));
    }

    public function findProductsInCartAndSortByTaxRate(
        int $cartId,
        int $clientId
    ) : array {
        return $this->createQueryBuilder('c')
            ->addSelect('p')
            ->addSelect('tr')
            ->innerJoin('c.product', 'p')
            ->innerJoin('p.taxRate', 'tr')
            ->where('c.cartId = :cartId')
            ->andWhere('c.clientId = :clientId')
            ->setParameter('cartId', $cartId)
            ->setParameter('clientId', $clientId)
            ->orderBy('tr.value', 'ASC')
            ->addOrderBy('c.id', 'ASC')
            ->getQuery()
            ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY)
        ;
    }

    public function findById(
        int $id,
        int $cartId,
        int $clientId
    ) {
        return $this->findOneBy(array(
            'id' => $id,
            'cartId' => $cartId,
            'clientId' => $clientId
        ));
    }
}
