<?php

namespace FitatuBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOne(int $productId)
    {
        return $this->findOneBy(array(
            'id' => $productId,
        ));
    }
}
